"""edit nullable event_seat model

Revision ID: 16b7f0826c59
Revises: 46b34092d919
Create Date: 2026-08-07 23:55:26.518452

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '16b7f0826c59'
down_revision = '46b34092d919'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.alter_column('start_time',
               existing_type=mysql.DATETIME(),
               nullable=True)
        batch_op.alter_column('end_time',
               existing_type=mysql.DATETIME(),
               nullable=True)
        batch_op.alter_column('event_start_time',
               existing_type=mysql.DATETIME(),
               nullable=True)
        batch_op.alter_column('event_end_time',
               existing_type=mysql.DATETIME(),
               nullable=True)
        batch_op.alter_column('status',
               existing_type=mysql.ENUM('DRAFT', 'PUBLISHED', 'CANCELLED'),
               nullable=True)
        batch_op.alter_column('location_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
        batch_op.alter_column('company_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
        batch_op.alter_column('category_id',
               existing_type=mysql.INTEGER(),
               nullable=True)

    with op.batch_alter_table('event_seat', schema=None) as batch_op:
        batch_op.alter_column('seat_total',
               existing_type=mysql.INTEGER(),
               type_=sa.String(length=10),
               existing_nullable=False)

    with op.batch_alter_table('ticket', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('ticket_ibfk_7'), type_='foreignkey')
        batch_op.drop_column('event_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ticket', schema=None) as batch_op:
        batch_op.add_column(sa.Column('event_id', mysql.INTEGER(), autoincrement=False, nullable=False))
        batch_op.create_foreign_key(batch_op.f('ticket_ibfk_7'), 'event', ['event_id'], ['id'])

    with op.batch_alter_table('event_seat', schema=None) as batch_op:
        batch_op.alter_column('seat_total',
               existing_type=sa.String(length=10),
               type_=mysql.INTEGER(),
               existing_nullable=False)

    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.alter_column('category_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
        batch_op.alter_column('company_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
        batch_op.alter_column('location_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
        batch_op.alter_column('status',
               existing_type=mysql.ENUM('DRAFT', 'PUBLISHED', 'CANCELLED'),
               nullable=False)
        batch_op.alter_column('event_end_time',
               existing_type=mysql.DATETIME(),
               nullable=False)
        batch_op.alter_column('event_start_time',
               existing_type=mysql.DATETIME(),
               nullable=False)
        batch_op.alter_column('end_time',
               existing_type=mysql.DATETIME(),
               nullable=False)
        batch_op.alter_column('start_time',
               existing_type=mysql.DATETIME(),
               nullable=False)

    # ### end Alembic commands ###
