"""edit event_seat model

Revision ID: 46b34092d919
Revises: caa82bcfc8fc
Create Date: 2026-08-07 22:43:07.216714

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '46b34092d919'
down_revision = 'caa82bcfc8fc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event_seat', schema=None) as batch_op:
        batch_op.alter_column('seat_total',
               existing_type=mysql.VARCHAR(length=10),
               type_=sa.Integer(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event_seat', schema=None) as batch_op:
        batch_op.alter_column('seat_total',
               existing_type=sa.Integer(),
               type_=mysql.VARCHAR(length=10),
               existing_nullable=False)

    # ### end Alembic commands ###
