"""add is_chatbox_enable to event

Revision ID: 66c76f43dd9d
Revises: 7cd4b990aec4
Create Date: 2026-09-07 18:20:38.348853

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '66c76f43dd9d'
down_revision = '7cd4b990aec4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_chatbox_enabled', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.drop_column('is_chatbox_enabled')

    # ### end Alembic commands ###
