"""add creator_id to event

Revision ID: 720676f38d4b
Revises: 7cd4b990aec4
Create Date: 2026-09-07 15:29:40.153065

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '720676f38d4b'
down_revision = '7cd4b990aec4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.add_column(sa.Column('creator_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'user', ['creator_id'], ['id'])

    with op.batch_alter_table('ticket', schema=None) as batch_op:
        batch_op.add_column(sa.Column('face_image', sa.String(length=255), nullable=False))

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('role',
               existing_type=mysql.ENUM('ADMIN', 'USER', 'STAFF'),
               type_=sa.Enum('ADMIN', 'USER', 'STAFF', 'PENDING', name='roleenum'),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('role',
               existing_type=sa.Enum('ADMIN', 'USER', 'STAFF', 'PENDING', name='roleenum'),
               type_=mysql.ENUM('ADMIN', 'USER', 'STAFF'),
               existing_nullable=False)

    with op.batch_alter_table('ticket', schema=None) as batch_op:
        batch_op.drop_column('face_image')

    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('creator_id')

    # ### end Alembic commands ###
