""" migration

Revision ID: 7cd4b990aec4
Revises: 
Create Date: 2026-08-25 20:49:10.234215

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7cd4b990aec4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event_category', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event_category', schema=None) as batch_op:
        batch_op.drop_column('image')

    # ### end Alembic commands ###
