"""remove purchase_time

Revision ID: 9017eed69228
Revises: 
Create Date: 2026-08-08 09:32:33.947462

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '9017eed69228'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ticket', schema=None) as batch_op:
        batch_op.drop_column('purchase_time')
        batch_op.drop_column('status')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ticket', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', mysql.ENUM('PENDING', 'SUCCESS', 'FAILED'), nullable=False))
        batch_op.add_column(sa.Column('purchase_time', mysql.DATETIME(), nullable=False))

    # ### end Alembic commands ###
