"""edit event model

Revision ID: 9147a1d2fb43
Revises: 73e7e73d079a
Create Date: 2026-08-07 21:56:49.826863

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '9147a1d2fb43'
down_revision = '73e7e73d079a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('discount', schema=None) as batch_op:
        batch_op.add_column(sa.Column('event_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'event', ['event_id'], ['id'])

    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.add_column(sa.Column('max_per_user', sa.Integer(), nullable=True))
        batch_op.alter_column('name',
               existing_type=mysql.VARCHAR(length=100),
               type_=sa.String(length=255),
               existing_nullable=False)
        batch_op.alter_column('status',
               existing_type=mysql.ENUM('DRAFT', 'PUBLISHED', 'CANCELLED'),
               nullable=False)

    with op.batch_alter_table('event_seat', schema=None) as batch_op:
        batch_op.add_column(sa.Column('seat_total', sa.String(length=10), nullable=False))
        batch_op.add_column(sa.Column('price', sa.Float(), nullable=False))
        batch_op.drop_column('seat_number')

    with op.batch_alter_table('ticket', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('ticket_ibfk_4'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('ticket_ibfk_2'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('ticket_ibfk_3'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'seat', ['seat_id'], ['id'])
        batch_op.drop_column('event_id')
        batch_op.drop_column('ticket_type_id')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('company_id', sa.Integer(), nullable=True))
        batch_op.alter_column('email',
               existing_type=mysql.VARCHAR(length=50),
               nullable=False)
        batch_op.alter_column('role',
               existing_type=mysql.ENUM('ADMIN', 'USER', 'STAFF'),
               nullable=False)
        batch_op.create_foreign_key(None, 'company', ['company_id'], ['id'])
        batch_op.drop_column('hobbies')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('hobbies', mysql.VARCHAR(length=255), nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('role',
               existing_type=mysql.ENUM('ADMIN', 'USER', 'STAFF'),
               nullable=True)
        batch_op.alter_column('email',
               existing_type=mysql.VARCHAR(length=50),
               nullable=True)
        batch_op.drop_column('company_id')

    with op.batch_alter_table('ticket', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ticket_type_id', mysql.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('event_id', mysql.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('ticket_ibfk_3'), 'event_seat', ['seat_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('ticket_ibfk_2'), 'event', ['event_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('ticket_ibfk_4'), 'event_ticket_type', ['ticket_type_id'], ['id'])

    with op.batch_alter_table('event_seat', schema=None) as batch_op:
        batch_op.add_column(sa.Column('seat_number', mysql.VARCHAR(length=10), nullable=False))
        batch_op.drop_column('price')
        batch_op.drop_column('seat_total')

    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=mysql.ENUM('DRAFT', 'PUBLISHED', 'CANCELLED'),
               nullable=True)
        batch_op.alter_column('name',
               existing_type=sa.String(length=255),
               type_=mysql.VARCHAR(length=100),
               existing_nullable=False)
        batch_op.drop_column('max_per_user')

    with op.batch_alter_table('discount', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('event_id')

    # ### end Alembic commands ###
