"""update otp_hash_code 

Revision ID: 95f5b1d5e60e
Revises: a23d6d92fe77
Create Date: 2026-08-09 11:38:12.139574

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '95f5b1d5e60e'
down_revision = 'a23d6d92fe77'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('email_otp', schema=None) as batch_op:
        batch_op.alter_column('otp_code_hash',
               existing_type=mysql.VARCHAR(length=6),
               type_=sa.String(length=255),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('email_otp', schema=None) as batch_op:
        batch_op.alter_column('otp_code_hash',
               existing_type=sa.String(length=255),
               type_=mysql.VARCHAR(length=6),
               existing_nullable=False)

    # ### end Alembic commands ###
